#!/bin/bash

log() {
  echo "dotenv-samplefile-autosync:" "$@"
}

log "running postinstall ..."

if [ -z "$INIT_CWD" ]; then
  log "not running in npm install context, skipping"
  exit 0
fi

PKG_DIR="$(pwd)"
cd "$INIT_CWD"

# Create .gitignore if it doesn't exist
if [ ! -f ".gitignore" ]; then
  touch ".gitignore"
  log "created .gitignore"
fi

# Ensure git is tracking .env*.sample files
if ! grep -q '!.env\*.sample' .gitignore; then
  echo -e '\n!.env*.sample' >> .gitignore
  log "ensured we're tracking .env*.sample files"
fi

cp "$PKG_DIR/scripts/pre-push" .git/hooks/pre-push
chmod +x .git/hooks/pre-push
log "installed pre-push hook; you're all set!"
